### ISSUE TITLE
Add network functionality

### ISSUE THREAD

**Issue by DaweMolnar** [Decesso/sdl-tetris#32]

**Comment by DaweMolnar** [comment]
- [x] Create gameserver script, for communication between clients #50
- [x]  Connect to the other client, with startgame message sent #53 
- [x]  Create Logic interface for passive logic #9 
- [x]  Create network controllers #54
- [x]  Send chosen characters to each other #58 
- [x]  Send mana #60
- [x]  Send game ending message #62
- [x]  Send special skill usage #64
- [x]  Send line number to add #64
- [x] Send the game area of the client to the other #65
